/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package app.view;

import app.controler.Catraca;
import app.controler.comparators.ComparatorEmailCliente;
import app.controler.GerenciamentoCliente;
import app.controler.Loja;
import app.model.Adm;
import app.model.Cliente;
import app.view.ViewBalanco;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author manuc
 */
public class ViewVerificadorEmail extends javax.swing.JFrame {
    
    GerenciamentoCliente gc = new GerenciamentoCliente();
    ComparatorEmailCliente emailComparator = new ComparatorEmailCliente();
    Menu menu = new Menu();
    private int tipoVerificacao;
    Catraca catraca = new Catraca();


    /**
     * Creates new form ViewVerificadorEmail
     */

    public ViewVerificadorEmail(int tipoVerificacao) {
        this.tipoVerificacao = tipoVerificacao;
        initComponents();
    }

    public ViewVerificadorEmail() {
    }
    
    
    
    public int clientesPresentes(){
        return catraca.mostrarNumeroClientesAtivos();}
    
    private boolean verificarEntrada(){
        
        Iterator<Cliente> iterator = gc.getListaDeClientes().iterator();
        while (iterator.hasNext()) {
            
            Cliente cliente = iterator.next();
            
            if (emailComparator.compare(cliente, new Cliente(fieldEmail.getText())) == 0) {
               catraca.adicionarLog(cliente.getName(), cliente.getEmail(), "Entrou");
               catraca.aumentarClienteAtivo();
               return true;
            }
        }
        return false;
    }
    
    private boolean verificarSaida(){
        
        Iterator<Cliente> iterator = gc.getListaDeClientes().iterator();
        while (iterator.hasNext()) {
            
            Cliente cliente = iterator.next();
            
            if (emailComparator.compare(cliente, new Cliente(fieldEmail.getText())) == 0) {
               catraca.adicionarLog(cliente.getName(), cliente.getEmail(), "Saiu");
               catraca.diminuirClienteAtivo();
               return true;
            } 
        }
        return false;
    }
    
    private boolean verificarSenhaAdm(){
        if(fieldEmail.getText().equals(Adm.getSenhaDeAdministrador())){
            return true;
        }
        return false;
    }
    
    
    private void chamarBotao(){
        if(tipoVerificacao == 1){
            
            if(verificarEntrada()){
                
               JOptionPane.showMessageDialog(null, "Entrada liberada");
               this.dispose();
               
            } else{
                
                JOptionPane.showMessageDialog(null, "Email invalido");
               this.dispose();
            }
        }
        
        if(tipoVerificacao == 2){
            
            if(verificarSaida()){
               
               JOptionPane.showMessageDialog(null, "Saida liberada"); 
               this.dispose();
               
            } else{
                
                JOptionPane.showMessageDialog(null, "Email invalido");
               this.dispose();
               
            }
        }
        if(tipoVerificacao ==3){
            if(verificarSenhaAdm()){
                JOptionPane.showMessageDialog(null, "Acesso liberado"); 
               this.dispose();
               ViewBalanco vb = new ViewBalanco();
               vb.setVisible(true);
               
            }else{
                
                JOptionPane.showMessageDialog(null, "Senha invalida");
                this.dispose();
               
            }
        }
        if(tipoVerificacao == 4){
            if(verificarSenhaAdm()){
                JOptionPane.showMessageDialog(null, "Acesso liberado"); 
                this.dispose();
                ViewGerenciamentoFuncionario vgf = new ViewGerenciamentoFuncionario();
                vgf.setVisible(true);
               
            }else{
                
                JOptionPane.showMessageDialog(null, "Senha invalida");
                this.dispose();
               
            }
        }
    }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fieldEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Digite seu e-mail ou senha de administrador");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        chamarBotao();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVerificadorEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVerificadorEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVerificadorEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVerificadorEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVerificadorEmail(0).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}


